name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name 'Shanewas Ahmed'
          git config --global user.email 'shanewasahmed@gmail.com'

      - name: Get current version
        id: get_current_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

      - name: Get previous version
        id: get_previous_version
        run: echo "::set-output name=version::$(git show origin/master:package.json | jq -r .version)"

      - name: Set job name
        uses: actions/github-script@v6
        with:
          script: |
            const currentVersion = '${{ steps.get_current_version.outputs.version }}';
            return `Publish to npm (version ${currentVersion})`;

      - name: Check version change
        id: version_check
        run: |
          if [ "${{ steps.get_current_version.outputs.version }}" == "${{ steps.get_previous_version.outputs.version }}" ]; then
            echo "Version has not changed. Skipping publish."
            exit 0
          fi

      - name: Push changes
        run: |
          git push --follow-tags origin master

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        if: steps.version_check.outputs.version != ''
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
